# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker


trigger:
  branches:
    include:
    - features/*
  paths:
    include:
    - apis/user-java/*

resources:
- repo: self

name: User Java API

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'bb8f9bf5-a939-49a6-bb6d-a2c99452888b'
  imageRepository: 'userjava'
  containerRegistry: 'openhack3mr4acr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/apis/user-java/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build Image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        tags: |
          $(tag)
