# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# specific path build
trigger:
  branches:
    include:
    - master
    - feature/*
  paths:
    include:
    - apis/user-java/*

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '593474d4-1b31-441a-838b-adcd84a14eb0'
  imageRepository: 'devopsoh/api-user-java'
  containerRegistry: 'openhackydy7auy8acr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/apis/user-java/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build And Unit Test
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        command: 'build'
        Dockerfile: '$(dockerfilePath)'
        arguments: "-t temp-image:$(tag) --target build-env"
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          docker create --name temp-container temp-image:$(tag)
          docker cp temp-container:/target/surefire-reports/ $(Build.ArtifactStagingDirectory)/testresults 
          docker rm -fv temp-container
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/*.xml'
        searchFolder: '$(Build.ArtifactStagingDirectory)/testresults'
        mergeTestResults: true
        testRunTitle: 'Unit Tests(MockIt)'
- stage: Build_Final
  displayName: Build Runtime Image
  jobs:  
  - job: Publish_Image
    displayName: Build and Publish Image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build And Push Image
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
